# Generated by Django 3.2.15 on 2023-02-27 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=100, verbose_name='Nom')),
            ],
        ),
        migrations.CreateModel(
            name='Couleur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_name', models.CharField(max_length=100, verbose_name='Couleur')),
                ('co_effet', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Pourcentage')),
                ('co_caracteristique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='co_caracteristique_name', to='calculator.caracteristique', verbose_name='Caractéristiques')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(max_length=50, verbose_name='Nom')),
                ('g_effet', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Pourcentage')),
                ('g_caracteristique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='g_caracteristique', to='calculator.caracteristique', verbose_name='Caractéristiques')),
            ],
        ),
        migrations.CreateModel(
            name='Palier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_numero', models.IntegerField(verbose_name='Numeros')),
                ('p_nombre_medailles', models.IntegerField(verbose_name='Nombre de médailles')),
            ],
        ),
        migrations.CreateModel(
            name='TypeEffet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ListeMedaille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_name', models.CharField(max_length=200, verbose_name='Nom')),
                ('l_bonus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_bonus', to='calculator.caracteristique', verbose_name='BONUS')),
                ('l_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_liste_medaille', to='calculator.couleur', verbose_name='Couleur')),
                ('l_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='l_grade_effect', to='calculator.grade', verbose_name='Grade')),
                ('l_malus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_malus', to='calculator.caracteristique', verbose_name='MALUS')),
            ],
        ),
        migrations.AddField(
            model_name='grade',
            name='g_type_effet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t_grade_type_effet', to='calculator.typeeffet', verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='couleur',
            name='co_palier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_couleur', to='calculator.palier', verbose_name='Palier'),
        ),
        migrations.CreateModel(
            name='Combinaison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_name', models.CharField(max_length=200, verbose_name='Nom')),
                ('com_effets', models.TextField(max_length=500, verbose_name='Résultat')),
                ('com_medailles', models.ManyToManyField(related_name='com_liste_medailles', to='calculator.ListeMedaille', verbose_name='Médailles')),
            ],
        ),
    ]
