# Generated by Django 3.2.15 on 2023-02-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='g_effet',
            field=models.IntegerField(verbose_name='Valeur effet'),
        ),
        migrations.AlterField(
            model_name='typeeffet',
            name='t_name',
            field=models.CharField(max_length=10, verbose_name='Type'),
        ),
    ]
