# Generated by Django 3.2.15 on 2023-02-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_alter_grade_g_effet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='g_effet',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Valeur effet'),
        ),
    ]
